import { db, findUserById, getTutorProfile, averageRating, paginate, loadPost, loadTransaction, decorateUser } from '../../core/services.js';
import { wrapPage, renderPager, csrfInput, emptyState, stars, formatMoney, formatDate, formatDateTime, relativeTime, limit, capitalize, escapeHtml } from '../layout.js';

function renderAdminUsers(context) {
  let users = db.prepare("SELECT * FROM users WHERE role IN ('learner', 'tutor') ORDER BY created_at DESC").all().map(decorateUser);
  if (context.query.role) users = users.filter((user) => user.role === context.query.role);
  if (context.query.status) users = users.filter((user) => user.status === context.query.status);
  if (context.query.search) users = users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(context.query.search.toLowerCase()));
  const page = paginate(users, context.query.page || 1, 15);
  return wrapPage(context, "User Directory", `<header class="page-head"><div><h1>User Directory</h1></div></header><form class="filters admin-filters"><input name="search" placeholder="Search name or email" value="${escapeHtml(context.query.search || "")}"><select name="role"><option value="">All roles</option><option ${context.query.role === "learner" ? "selected" : ""}>learner</option><option ${context.query.role === "tutor" ? "selected" : ""}>tutor</option></select><select name="status"><option value="">All statuses</option><option ${context.query.status === "active" ? "selected" : ""}>active</option><option ${context.query.status === "pending" ? "selected" : ""}>pending</option><option ${context.query.status === "deactivated" ? "selected" : ""}>deactivated</option></select><button class="btn">Filter</button></form><table class="admin-table"><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr>${page.items.length ? page.items.map((user) => `<tr><td><div class="user-cell"><img class="tiny" src="${escapeHtml(user.avatar_url)}"><div><b>${escapeHtml(user.name)}</b><br><small class="soft">${escapeHtml(user.email)}</small></div></div></td><td><span class="badge ${user.role === "tutor" ? "purple" : "blue"}">${capitalize(user.role)}</span></td><td><span class="badge">${capitalize(user.status)}</span></td><td><div class="table-actions"><a class="btn ghost sm" href="/admin/users/${user.id}">View</a><form method="post" action="/admin/users/${user.id}/${user.status === "deactivated" ? "reactivate" : "deactivate"}" data-confirm="${user.status === "deactivated" ? "Reactivate this user account?" : "Deactivate this user account?"}">${csrfInput(context)}<button class="btn sm ${user.status === "deactivated" ? "" : "danger"}">${user.status === "deactivated" ? "Reactivate" : "Deactivate"}</button></form><form method="post" action="/admin/users/${user.id}/reset-password" data-confirm="Reset this user password?">${csrfInput(context)}<button class="btn ghost sm">Reset Password</button></form><form method="post" action="/admin/users/${user.id}" data-confirm="Delete this user permanently? This cannot be undone.">${csrfInput(context)}<input type="hidden" name="_method" value="DELETE"><button class="btn danger sm">Delete</button></form></div></td></tr>`).join("") : `<tr><td colspan="4">${emptyState("No records found", "")}</td></tr>`}</table>${renderPager(context.url.pathname, context.query, page)}`);
}

function renderAdminAccounts(context) {
  const admins = db.prepare("SELECT * FROM users WHERE role = 'admin' ORDER BY created_at DESC").all().map(decorateUser);
  return wrapPage(context, "Admin Accounts", `<header class="page-head"><h1>Admin Accounts</h1></header><section class="admin-account-layout"><form class="panel admin-create-card" method="post" action="/admin/users/create">${csrfInput(context)}<div class="form-heading"><span class="form-icon">+</span><div><h2>Create Admin Account</h2></div></div><div class="grid-2"><label>Name<input name="name" required placeholder="Admin full name"></label><label>Email<input name="email" type="email" required placeholder="admin@example.com"></label></div><div class="grid-2"><label>Password<input name="password" type="password" required placeholder="Minimum 8 characters"></label><label>Confirm Password<input name="password_confirmation" type="password" required placeholder="Repeat password"></label></div><button class="btn">Create Admin</button></form><section class="panel admin-list-card"><h2>Existing Admin Accounts</h2><table class="admin-table"><tr><th>Admin</th><th>Status</th><th>Created</th><th>Actions</th></tr>${admins.length ? admins.map((admin) => `<tr><td><div class="user-cell"><img class="tiny" src="${escapeHtml(admin.avatar_url)}"><div><b>${escapeHtml(admin.name)}</b><br><small class="soft">${escapeHtml(admin.email)}</small></div></div></td><td><span class="badge">${capitalize(admin.status)}</span></td><td>${escapeHtml(formatDate(admin.created_at))}</td><td><div class="table-actions"><a class="btn ghost sm" href="/admin/users/${admin.id}">View</a>${admin.id !== context.user.id ? `<form method="post" action="/admin/users/${admin.id}/${admin.status === "deactivated" ? "reactivate" : "deactivate"}" data-confirm="${admin.status === "deactivated" ? "Reactivate this admin account?" : "Deactivate this admin account?"}">${csrfInput(context)}<button class="btn sm ${admin.status === "deactivated" ? "" : "danger"}">${admin.status === "deactivated" ? "Reactivate" : "Deactivate"}</button></form><form method="post" action="/admin/users/${admin.id}/reset-password" data-confirm="Reset this admin password?">${csrfInput(context)}<button class="btn ghost sm">Reset Password</button></form><form method="post" action="/admin/users/${admin.id}" data-confirm="Delete this admin account permanently?">${csrfInput(context)}<input type="hidden" name="_method" value="DELETE"><button class="btn danger sm">Delete</button></form>` : '<span class="soft current-account">Current account</span>'}</div></td></tr>`).join("") : `<tr><td colspan="4">${emptyState("No admin accounts found", "")}</td></tr>`}</table></section></section>`);
}

function renderAdminTutors(context) {
  const tutors = db.prepare("SELECT * FROM users WHERE role = 'tutor' AND status = 'pending' ORDER BY created_at DESC").all().map((user) => ({ ...decorateUser(user), tutorProfile: getTutorProfile(user.id) }));
  return wrapPage(context, "Tutor Approvals", `<header class="page-head"><div><h1>Tutor Approvals</h1></div></header><table class="admin-table"><tr><th>Tutor</th><th>Subjects</th><th>Rate</th><th>Actions</th></tr>${tutors.length ? tutors.map((user) => `<tr><td><div class="user-cell"><img class="tiny" src="${escapeHtml(user.avatar_url)}"><div><b>${escapeHtml(user.name)}</b><br><small class="soft">${escapeHtml(user.email)}</small></div></div></td><td>${escapeHtml(user.tutorProfile?.subjects_offered || "Not filled yet")}</td><td>${user.tutorProfile?.hourly_rate ? `&#8369;${formatMoney(user.tutorProfile.hourly_rate)}` : "Not set"}</td><td><div class="table-actions"><form method="post" action="/admin/tutors/${user.id}/approve" data-confirm="Approve this tutor account?">${csrfInput(context)}<button class="btn sm">Approve</button></form><form class="reason-action" method="post" action="/admin/tutors/${user.id}/decline" data-confirm="Decline this tutor account?">${csrfInput(context)}<input name="reason" placeholder="Decline reason" required><button class="btn danger sm">Decline</button></form></div></td></tr>`).join("") : `<tr><td colspan="4">${emptyState("No pending approvals", "")}</td></tr>`}</table>`);
}

export {
  renderAdminUsers,
  renderAdminAccounts,
  renderAdminTutors
};
